# Example values for Flight Simulator 2020.
# Update these as necessary.
keys:
  - PLANE_ALTITUDE
  - GROUND_VELOCITY
  - AIRSPEED_INDICATED
  - AIRSPEED_MACH
  - AMBIENT_TEMPERATURE
  - AMBIENT_PRESSURE
  - TOTAL_WEIGHT
  - FUEL_TOTAL_QUANTITY
  - ENG_FUEL_FLOW_GPH:1
  - ENG_FUEL_FLOW_GPH:2
  - TURB_ENG_CORRECTED_N1:1
  - TURB_ENG_CORRECTED_N2:1
  - VERTICAL_SPEED
  - AIRCRAFT_WIND_X
  - AIRCRAFT_WIND_Y